### ISSUE TITLE
Tutorial not working

### ISSUE THREAD

**Issue by ahenkes1** [SciML/NeuralPDE.jl#181]
I tried the 2D Poisson's equation Tutorial [()](https://neuralpde.sciml.ai/dev/examples/pinns_example/) and got the following error executing the solver:

`julia> res = GalacticOptim.solve(prob, BFGS(), progress = false; cb = cb, maxiters=1000)

ERROR: MethodError: no method matching Optim.Options(; extended_trace=true, callback=GalacticOptim.var"#_cb#25"{var"#1#2",BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat},Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}}(var"#1#2"(), BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}(LineSearches.InitialStatic{Float64}
  alpha: Float64 1.0
  scaled: Bool false
, LineSearches.HagerZhang{Float64,Base.RefValue{Bool}}
  delta: Float64 0.1
  sigma: Float64 0.9
  alphamax: Float64 Inf
  rho: Float64 5.0
  epsilon: Float64 1.0e-6
  gamma: Float64 0.66
  linesearchmax: Int64 50
  psi3: Float64 0.1
  display: Int64 0
  mayterminate: Base.RefValue{Bool}
, nothing, nothing, Flat()), Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}((GalacticOptim.NullData(),)), Core.Box(2), Core.Box(GalacticOptim.NullData()), Core.Box(#undef)), iterations=1000, progress=false)
Closest candidates are:
  Optim.Options(; x_tol, f_tol, g_tol, x_abstol, x_reltol, f_abstol, f_reltol, g_abstol, g_reltol, outer_x_tol, outer_f_tol, outer_g_tol, outer_x_abstol, outer_x_reltol, outer_f_abstol, outer_f_reltol, outer_g_abstol, outer_g_reltol, f_calls_limit, g_calls_limit, h_calls_limit, allow_f_increases, allow_outer_f_increases, successive_f_tol, iterations, outer_iterations, store_trace, trace_simplex, show_trace, extended_trace, show_every, callback, time_limit) at /home/ah/.julia/packages/Optim/auGGa/src/types.jl:73 got unsupported keyword argument "progress"
  Optim.Options(::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::Int64, ::Int64, ::Int64, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::TCallback, ::Float64) where {T, TCallback} at /home/ah/.julia/packages/Optim/auGGa/src/types.jl:44 got unsupported keyword arguments "extended_trace", "callback", "iterations", "progress"
Stacktrace:
 [1] kwerr(::NamedTuple{(:extended_trace, :callback, :iterations, :progress),Tuple{Bool,GalacticOptim.var"#_cb#25"{var"#1#2",BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat},Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}},Int64,Bool}}, ::Type{T} where T) at ./error.jl:157
 [2] __solve(::OptimizationProblem{true,OptimizationFunction{true,GalacticOptim.AutoZygote,NeuralPDE.var"#loss_function#191"{NeuralPDE.var"#177#183"{Int64,NeuralPDE.var"#175#181"{NeuralPDE.var"#168#170"{FastChain{Tuple{FastDense{typeof(σ),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(σ),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}}}}},NeuralPDE.var"#172#173"{Float32},NeuralPDE.var"#inner_loss#179"}},NeuralPDE.var"#177#183"{Int64,NeuralPDE.var"#175#181"{NeuralPDE.var"#168#170"{FastChain{Tuple{FastDense{typeof(σ),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(σ),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}},FastDense{typeof(identity),DiffEqFlux.var"#initial_params#73"{typeof(Flux.glorot_uniform),typeof(Flux.zeros),Int64,Int64}}}}},NeuralPDE.var"#172#173"{Float32},NeuralPDE.var"#inner_loss#179"}}},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float32,1},DiffEqBase.NullParameters,Nothing,Nothing,Nothing,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}}, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}, ::Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}; cb::Function, maxiters::Int64, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:progress,),Tuple{Bool}}}) at /home/ah/.julia/packages/GalacticOptim/TfGcK/src/solve.jl:208
 [3] #solve#1 at /home/ah/.julia/packages/GalacticOptim/TfGcK/src/solve.jl:12 [inlined]
 [4] top-level scope at REPL[16]:1
`
Should the tutorial code be updated or is there another problem?

**Comment by ChrisRackauckas** [comment]
Are you on Julia v1.5 with the latest versions of the packages? What is your `]st`?

**Comment by ahenkes1** [comment]
`(@v1.5) pkg> st
Status `~/.julia/environments/v1.5/Project.toml`
  [aae7a2af] DiffEqFlux v1.25.0
  [587475ba] Flux v0.11.2
  [a75be94c] GalacticOptim v0.4.2
  [961ee093] ModelingToolkit v4.0.6
  [315f7962] NeuralPDE v2.6.0
  [429524aa] Optim v1.2.0
`

**Comment by ChrisRackauckas** [comment]
Oh, the dev tutorials are not the current release. I'll just tag.

**Comment by ChrisRackauckas** [comment]
Should be fixed by NeuralPDE release v2.7

**Comment by ahenkes1** [comment]
Error remains with new version:

`Status `~/.julia/environments/v1.5/Project.toml`
  [aae7a2af] DiffEqFlux v1.25.0
  [587475ba] Flux v0.11.2
  [a75be94c] GalacticOptim v0.4.2
  [4df31cd9] Grassmann v0.7.1
  [ee78f7c6] Makie v0.11.1
  [961ee093] ModelingToolkit v4.0.6
  [315f7962] NeuralPDE v2.7.0
  [429524aa] Optim v1.2.0
`

**Comment by asdasdqwdqwfsdf** [comment]
@ChrisRackauckas 
can we solve **3D** Poisson's equation problems here?

**Comment by ChrisRackauckas** [comment]
yes

**Comment by ChrisRackauckas** [comment]
@ahenkes1 did you get this working?

**Comment by ahenkes1** [comment]
Error is still there with v.3.0.0

**Comment by ChrisRackauckas** [comment]
Do you have GalacticOptim.jl v0.4.2?

**Comment by ahenkes1** [comment]
Yes

 `ae7a2af] DiffEqFlux v1.26.0
  [587475ba] Flux v0.11.2
  [a75be94c] GalacticOptim v0.4.2
  [4df31cd9] Grassmann v0.7.1
  [ee78f7c6] Makie v0.11.1
  [961ee093] ModelingToolkit v4.2.0
  [315f7962] NeuralPDE v3.0.0
  [429524aa] Optim v1.2.0
`

**Comment by OVGULIU** [comment]
> yes

@ChrisRackauckas  is there  a good way that we can plot the **3D** poisson results **_using PLOTS_** (\phi in X,Y,Z)?

**Comment by ChrisRackauckas** [comment]
Yes. If you look at the examples it shows how to plot, and if you want to do a 3D plot, just plot with 3 portions, i.e. `plot(xs,ys,zs)` and make it a heatmap or whatever you want. That's a question on using the plotting libraries and better served in https://discourse.julialang.org/ . Please do not post questions like that in unrelated issues.

**Comment by ChrisRackauckas** [comment]
@ahenkes1 thanks for the issue. The problem in the latest version was that `progress` was an arguement that was handled with Flux optimizers but not Optim optimizers in GalacticOptim.jl. For the tutorial, since it's unnecessary, I just removed the `progress=true ` in https://github.com/SciML/NeuralPDE.jl/commit/01069f7c133b30e268eccc13ed5f5c8264bb98c3 and that should be fine. To make this more robust, I did https://github.com/SciML/GalacticOptim.jl/pull/83 so that if you pass `progress` to an Optim optimizer it won't error.

Thanks for the report as it helped make it easy to track down!

**Comment by ahenkes1** [comment]
@ChrisRackauckas unfortunately this did not resolve the issue. I post the exact error:

`julia> res = GalacticOptim.solve(prob, BFGS(), progress = false; cb = cb, maxiters=1000)
ERROR: MethodError: no method matching Optim.Options(; extended_trace=true, callback=GalacticOptim.var"#_cb#25"{var"#1#2",BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat},Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}}(var"#1#2"(), BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}(LineSearches.InitialStatic{Float64}
  alpha: Float64 1.0
  scaled: Bool false
, LineSearches.HagerZhang{Float64,Base.RefValue{Bool}}
  delta: Float64 0.1
  sigma: Float64 0.9
  alphamax: Float64 Inf
  rho: Float64 5.0
  epsilon: Float64 1.0e-6
  gamma: Float64 0.66
  linesearchmax: Int64 50
  psi3: Float64 0.1
  display: Int64 0
  mayterminate: Base.RefValue{Bool}
, nothing, nothing, Flat()), Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}((GalacticOptim.NullData(),)), Core.Box(2), Core.Box(GalacticOptim.NullData()), Core.Box(#undef)), iterations=1000, progress=false)
Closest candidates are:
  Optim.Options(; x_tol, f_tol, g_tol, x_abstol, x_reltol, f_abstol, f_reltol, g_abstol, g_reltol, outer_x_tol, outer_f_tol, outer_g_tol, outer_x_abstol, outer_x_reltol, outer_f_abstol, outer_f_reltol, outer_g_abstol, outer_g_reltol, f_calls_limit, g_calls_limit, h_calls_limit, allow_f_increases, allow_outer_f_increases, successive_f_tol, iterations, outer_iterations, store_trace, trace_simplex, show_trace, extended_trace, show_every, callback, time_limit) at /home/ah/.julia/packages/Optim/auGGa/src/types.jl:73 got unsupported keyword argument "progress"
  Optim.Options(::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::T, ::Int64, ::Int64, ::Int64, ::Bool, ::Bool, ::Int64, ::Int64, ::Int64, ::Bool, ::Bool, ::Bool, ::Bool, ::Int64, ::TCallback, ::Float64) where {T, TCallback} at /home/ah/.julia/packages/Optim/auGGa/src/types.jl:44 got unsupported keyword arguments "extended_trace", "callback", "iterations", "progress"
Stacktrace:
 [1] kwerr(::NamedTuple{(:extended_trace, :callback, :iterations, :progress),Tuple{Bool,GalacticOptim.var"#_cb#25"{var"#1#2",BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat},Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}},Int64,Bool}}, ::Type{T} where T) at ./error.jl:157
 [2] __solve(::OptimizationProblem{true,OptimizationFunction{true,GalacticOptim.AutoZygote,NeuralPDE.var"#loss_function_#260",Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Float32,1},DiffEqBase.NullParameters,Nothing,Nothing,Nothing,Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}}, ::BFGS{LineSearches.InitialStatic{Float64},LineSearches.HagerZhang{Float64,Base.RefValue{Bool}},Nothing,Nothing,Flat}, ::Base.Iterators.Cycle{Tuple{GalacticOptim.NullData}}; cb::Function, maxiters::Int64, kwargs::Base.Iterators.Pairs{Symbol,Bool,Tuple{Symbol},NamedTuple{(:progress,),Tuple{Bool}}}) at /home/ah/.julia/packages/GalacticOptim/TfGcK/src/solve.jl:208
 [3] #solve#1 at /home/ah/.julia/packages/GalacticOptim/TfGcK/src/solve.jl:12 [inlined]
 [4] top-level scope at REPL[18]:1
`
As I am quite new to Julia, it is hard to track down the cause of the error myself.

**Comment by ChrisRackauckas** [comment]
I haven't released the fix yet, so you'd need to remove the `progress = false`. What code exactly did you run?

**Comment by ahenkes1** [comment]
Ok, i ran [this](https://neuralpde.sciml.ai/dev/examples/pinns_example/) code

**Comment by ChrisRackauckas** [comment]
Yes, and I just mentioned you shouldn't run that code and instead remove the `progress=false`. Did you do that?

**Comment by ahenkes1** [comment]
Everything works just fine now! Thank you for your patience!

**Comment by ChrisRackauckas** [comment]
Yeah no problem. Thanks for the report.
